redhat-cop/businessautomation-cop

- bcgithook/README.md
- bcgithook/scripts/default.conf.example
- bcgithook/scripts/post-commit.sh
Added configuration variable LOG_SYSTEM_REPOS to minimize logging while accessing PAM system repos.
Will result in less verbose logs that will contain operations performed only on user repositories/projects
> logging access to system repos is now configurable

- pam-eap-setup/pam-setup.sh
Dependency for "hostid" command was removed.
It is not required and it creates issues with Mac users.
> removed dependency for hostid command

- pam-eap-setup/.gitignore
- pam-eap-setup/README.md
- pam-eap-setup/pam-setup.sh
Tested in macOS. As macOS comes with an old version of `bash` in `/bin/bash` its recommended to use the env shebash as suggested here: https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html. Thus the script can use the correct version of bash on MacOS.
> adding support for DM 7.7.1 and other changes

- pam-quick-examples/dmn-example1/build.sh
- pam-quick-examples/dmn-example1/run.sh
- pam-quick-examples/dmn-example2/build.sh
- pam-quick-examples/dmn-example2/run.sh
- pam-quick-examples/dmn-example3/build.sh
- pam-quick-examples/dmn-example3/run.sh
- pam-quick-examples/dmn-example4/build.sh
- pam-quick-examples/dmn-example4/run.sh
- pam-quick-examples/dmn-example5/build.sh
- pam-quick-examples/dmn-example5/run.sh
- pam-quick-examples/dmn-example6/build.sh
- pam-quick-examples/dmn-example6/run.sh
Makes the scripts a bit more env friendly across linux/mac with multiple bash versions installed
> Changed pam examples bash shebangs to use env

- pam-eap-setup/pam-setup.sh
Fixing handling of options parameter. 
Potentially could ignore provided options for jvm_memory
Run ./pam-setup.sh without providing "jvm_memory" option. Defaults should be used.
> fix for potentially malhandling of jvm_memory option

- pam-eap-setup/pam-setup.sh
Checks have been introduced for verifying version of bash depending on OS before allowing the script to continue.
When executing on macOS or CygWin environment a notification should be displayed.
> added checks on bash version based on OS

- .github/workflows/mvn-pam-quick-examples.yaml
- pam-quick-examples/dmn-example4/run.sh
Adds shellcheck directly under pam examples. Currently it uses a fork of the shellcheck under my repo, as i need this PR merging:
- https://github.com/ludeeus/action-shellcheck/pull/15
So expect another PR in the future once they merge, and we can move back to upstream
> Added shellcheck to pam-examples ci

- .github/workflows/build-bcgithook.yaml
- .github/workflows/build-pam-eap-setup.yaml
Adds other OS's as test platforms. Should allow for platform testing of the below in the future:
- https://github.com/redhat-cop/businessautomation-cop/pull/108
Check action output
> Added other OS images for bcgithook / pam-eap-setup ci

- bcgithook/scripts/post-commit.sh
added OS and bash version detection to post-commit git hook script
When run in macOS or CygWin environment OS identification message should be logged
> added OS and bash version detection to git hook script

- bcgithook/install.sh
Added OS and Bash version detection to git hook installation script.
If OS or bash version are not up to par installation will abort and will not alter Business Central properties
Installation on an unsupported OS/bash version combination should fail. For example using bash version less than 4 or less than 5 in macOS.
> added OS detection to post-commit installation script

- bcgithook/scripts/default.conf.example
- bcgithook/scripts/post-commit.sh
Added ALLOW and DENY branches lists to post-commit git hooks.
Certain branches, such as master or release, can be excluded for being pushed to remote git repo while allowing only others, e.g. "devel"
Define BRANCH_ALLOW and/or BRANCH_DENY lists and try making changes in those branches
> added ALLOW and DENY branches list to git hooks

- .github/actions/eap-base/Dockerfile
- .github/actions/eap-base/action.yml
- .github/actions/eap-base/entrypoint.sh
- .github/workflows/build-pam-eap-setup.yaml
Downloads all the product zips needed by pam-eap-setup.sh and then executes the script to check its worked.
NOTE: As it uses secrets, future PRs won't be tested unless the raiser adds the required secrets to their fork.
My fork with creds: https://github.com/garethahealy/businessautomation-cop/runs/806824005?check_suite_focus=true
This PR without creds: https://github.com/redhat-cop/businessautomation-cop/pull/136/checks?check_run_id=806873240
> Added ansible to download eap zip for pam-eap-setup

- bcgithook/README.md
- bcgithook/scripts/default.conf.example
- bcgithook/scripts/post-commit.sh
- Adds flag to enable regex mode
- Updates documentation and README
- Adds example configuration
This PR adds the ability to specify a regular expression for the BRANCH_ALLOW variable.
There are 8 scenarios to test for, which can probably be better visualized as a truth table.
BRANCH_ALLOW_IS_REGEX=true
BRANCH_ALLOW=csv
BRANCH_DENY=non-empty
BRANCH_ALLOW_IS_REGEX=true
BRANCH_ALLOW=csv
BRANCH_DENY=empty
BRANCH_ALLOW_IS_REGEX=true
BRANCH_ALLOW=regex
BRANCH_DENY=non-empty
BRANCH_ALLOW_IS_REGEX=true
BRANCH_ALLOW=regex
BRANCH_DENY=empty
BRANCH_ALLOW_IS_REGEX=false
BRANCH_ALLOW=csv
BRANCH_DENY=non-empty
BRANCH_ALLOW_IS_REGEX=false
BRANCH_ALLOW=csv
BRANCH_DENY=empty
BRANCH_ALLOW_IS_REGEX=false
BRANCH_ALLOW=regex
BRANCH_DENY=non-empty
BRANCH_ALLOW_IS_REGEX=false
BRANCH_ALLOW=regex …
> Add RegEx handling to the BRANCH_ALLOW variable.

- bcgithook/README.md
- bcgithook/scripts/default.conf.example
- bcgithook/scripts/post-commit.sh
Refactoring application of regular expressions to the handling of branches in BC post-commit git hooks.
This implementation does not use the same variable for regex and non-regex cases making it easier to keep track of applicable conditions.
Documentation updated
Simplifies testing by having only ALLOW and DENY lists to check,
Regexes are handled the same as ALLOW.
> Refactoring branch handling with regexes in BC git hooks

- pam-eap-setup/pam-setup.sh
Added option for configuring RHPAM run mode as in "development" or "production".
The following system properties are affected:
- org.guvnor.project.gav.check.disabled
- org.kie.server.mode
Specify run_mode=production and property "org.kie.server.mode" should be set to "production" in standalone.xml
> added option for configuring RHPAM run mode

- pam-eap-setup/pam-setup.sh
pam-eap-setup checks for git, curl and maven are only needed for specific installation options. Checks for these have been refactored to be applied only when these installation options are specified.
Should install without git, curl or maven if no git hook option is specified
> refactored checks to apply only when called for

- pam-eap-setup/CHANGELOG
- pam-eap-setup/pam-setup.sh
A regression was spotted after the last commit.
When no installation path is provided or the installation path is not an absolute on the resulting RHPAM installation is not starting.
This commit addresses that.
Run with no installation path as an option and start RHPAM. it should start.
> fixed regression on empty installation path

- pam-eap-setup/pam-setup.sh
Specifying installation location containing symbolic links, relative/absolute paths  was not resolving correctly for all cases under all supported OSes.
Simplified installation location code across supported OSes
Installation should abide by the value provided in arguments
> fixed handling of edge cases for installation location

- .github/workflows/build-pam-eap-setup.yaml
As per $subject.
Gitub action scripts are now testing for RHPAM.7.8.0 on JBoss EAP.7.3.2
Action scripts should finish successfully. 
> updated pam-eap-setup github actions scripts to EAP.7.3.2 and PAM.7.8.0

- bcgithook/scripts/default.conf.example
- bcgithook/scripts/post-commit.sh
Added functionality to bcgithook post commit git hooks for mapping local BC branches to branches in the remote git repo with different name.
For example mapping "master" to "mainline"
Define BRANCH_MAP variable in config, for example BRANCH_MAP="master:mainline"
> Added branch mapping to bcgithook

- pam-eap-setup/pam-setup.sh
Added Java version detection in pam-eap-setup to stop installation from proceeding if installed Java version is not 1.8 or 11
Installation should not proceed if installed Java version is not 1.8 or 11
> added java version detection for pam-eap-setup

- .github/workflows/build-pam-eap-setup.yaml
- pam-eap-setup/README.md
- pam-eap-setup/pam-setup.sh
pam-eap-setup has been updated to handle RHDM and RHPAM 7.9.
Documentation has been updated as well.
Installation with version 7.9 should result in a working system.
> added support for RHDM and RHPAM 7.9

- pam-eap-setup/pam-setup.sh
Add RHDM.7.9.1 to the list of RHDM version handled by pam-eap-setup
> added RHDM.7.9.1 to pam-eap-setup

- deployment-examples/pam-eap-setup/README.md
- deployment-examples/pam-eap-setup/pam-setup.sh
pam-eap-setup allows for automatic installation of bcgithook from ba-cop repository.
This needs aligning with the new structure of the repository
git hooks should be installed by pam-eap-setup
> Align bcgithook installation by pam-eap-setup to new git structure

- deployment-examples/pam-eap-setup/README.md
- deployment-examples/pam-eap-setup/addons/access_log
- deployment-examples/pam-eap-setup/pam-setup.sh
- deployment-examples/pam-eap-setup/pam.config
- extras/bcgithook/README.md
- extras/bcgithook/install.sh
(1) pam-eap-setup can handle RHPAM.7.9.1, enables Prometheus endpoints by default and provides for access_log logging
(2) bcgithooks facilitates multiple installation by allowing configuration per installation on top of the global one
(3) Documentation updates for the new functionality
Use pam-eap-setup to install enabling bcgithooks and take advantage of per installation configuration
> Expand pam-eap-setup configuration options, per installation bcgithook configuration and documentation updates

- extras/pam-vagrant/README.md
- extras/pam-vagrant/bootstrap.sh
Fix the installation procedure used by pam-vagrant to handle RHDM as well as RHPAM
Use DecisionManager binaries to set up a vagrant box
> bugfix: pam-vagrant can now handle DecisionManager

- extras/pam-vagrant/bootstrap.sh
- extras/pam-vagrant/pam7-systemd-integration.sh
Installation of PAM as a systemd service accepts a user parameter for PAM to be installed into
PAM is no longer installed as the "jboss" user; the user is configurable 
> make user configurable for systemd installation of PAM

- deployment-examples/pam-eap-setup/pam-setup.sh
Update pam-eap-setup for RHPAM.7.10.0
RHPAM/RHDM 7.10.0 can now be installed
> updated for RHPAM.7.10.0

- coded-examples/spring-boot-examples/drools/drools-sboot-embedded/.gitignore
- coded-examples/spring-boot-examples/drools/drools-sboot-embedded/README.md
- coded-examples/spring-boot-examples/drools/drools-sboot-embedded/pom.xml
- coded-examples/spring-boot-examples/drools/drools-sboot-embedded/src/main/java/org/redhat/services/util/RoutingConstants.java
- coded-examples/spring-boot-examples/drools/drools-sboot-embedded/src/main/resources/application.yml
Fixing readme with the correct Consoles URLs
Fixing Camel swagger api-docs to test via Swagger UI
```
mvn clean compile spring-boot:run -Ph2 
```
and access the following URLs:
- Swagger JSON: http://localhost:8090/api/api-doc
- Swagger UI: http://localhost:8090/webjars/swagger-ui/index.html?url=/api/api-doc
- Spring Management (Actuator): http://localhost:8091/actuator/
- H2 Console: http://localhost:8090/h2-console
> Fixing readme console URLs and camel swagger api docs

- deployment-examples/pam-eap-setup/README.md
- deployment-examples/pam-eap-setup/pam-setup.sh
pam-eap-setup updated to handle RHDM.7.10.1
RHDM.7.10.1 should be able to be installed by pam-eap-setp
> pam-eap-setup updates for rhdm.7.10.1

- deployment-examples/pam-eap-setup/README.md
- deployment-examples/pam-eap-setup/pam-setup.sh
Installation option "bcgithook_config" has been added to pam_eap_setup allowing separate per RHPAM installation configuration or a "global" one for all RHPAM installations (in the same machine).
Update documentation.
Installing with "bcgithook_config=local" will install bcgithook configuration in a RHPAM installation specific directory
> Add installation option to pam_eap_setup for bcgithook configuration

- deployment-examples/pam-eap-setup/pam-setup.sh
Added RHPAM.7.11.0 support to pam-eap-setup
pam-eap-setup should be able to install RHPAM/RHDM.7.11 binaries
> Added RHPAM.7.11.0 support to pam-eap-setup

- extras/bcgithook/scripts/post-commit.sh
Support for ssh-git style URLs for git repos. e.g. git@gitlab.com:GIT_USER/GIT_PROJECT.git, has been added to post-commit git hooks
Using Business Central as an authoring tool with the bcgithook post-commit git hooks installed should be able to import and propagate changes to remote git repos that are accessed through ssh-git style URLs.
> Added support for ssh-git urls in post commit git hooks

- extras/bcgithook/scripts/post-commit.sh
Per-project configuration can now handle project specific URLs.
Previously only generic URLs could be handled which was often a source of confusion.
Git hooks should propagate changes when configured with project specific URL, e.g. 'git@gitlab.com:dundeeinc/delicioushaggis.git' as well as generic ones, e.g. 'git@gitlab.com:dundeeinc''
> allow project specific URLs for per-project configuration

- deployment-examples/pam-eap-setup/pam-setup.sh
Enable logging of projects and spaces deleltion in Business Central configured by pam-eap-setup as per KB6139932
When a project or space is deleted entries in the server.log should be found as per KB6139932
> enabled logging of spaces or projects deletion

- deployment-examples/pam-eap-setup/pam-setup.sh
Using the embedded in Business Central maven artefact repository without setting the "org.appformer.m2repo.url" results in an error logged without actually preventing BC from operating.
Setting that property prevents the error message logged.
Setting the "org.appformer.m2repo.url" property should prevent the following messages from being logged
WARN  [org.guvnor.m2repo.backend.server.M2RepoServiceImpl] (default task-2) The url null is not valid. Using the default.
ERROR [org.guvnor.m2repo.backend.server.M2RepoServiceImpl] (default task-2) The property org.appformer.m2repo.url is not correctly set. The workbench will use a direct file path to the m2 repository and this should only be used when test the workbench.
> added appformer m2 config

- deployment-examples/pam-eap-setup/pam-setup.sh
Deploying Business Central using pam-eap-setup does not set development mode unless another option (any option) is specified.
BC should be deployed in development mode by default regardless of other options being present or not.
The "org.kie.server.mode" parameter should be set to "development" without any options specified in the command line
> Deploy Business Central in development mode by default

- deployment-examples/using-the-rest-api/README.md
- deployment-examples/using-the-rest-api/config.properties
- deployment-examples/using-the-rest-api/deploy-kjar-bc.js
Added KIE Server credentials configuration.
The deploy-kjar-bc.js script no longer makes assumptions on the KIE Server credentials for validating KJAR deployment. Credentials must now be explicitly defined.
Wrong credentials would result in failure of checking against KIE Server
> added kie server credentials configuration

- deployment-examples/pam-eap-setup/pam-setup.sh
pam-eap-etup can provision unmanaged KIE Server on their own or in combination with managed KIE Servers
For instance, use the '-b custom=controller,kie,ukie' option and a controller a managed KIE Server as well as unmanaged one will be installed.
> Allow for unamanged KIE Servers

- coded-examples/dmn-examples/dmn-jbpm-ext-kjar-example/project/kjars/process-kjar/pom.xml
updating xstream to non-vulnerable version (1.4.19)
All unit tests should continue to pass
> updating xstream to non-vulnerable version

- deployment-examples/pam-eap-setup/pam-setup.sh
Changes made to pam-eap-setup to accommodate RHPAM.7.12 prevented earlier versions from being installed.
These changes have been temporarily reverted to until the issue is resolved.
RHPAM versions 7.11.1 and earlier should now be able to get installed.
> reverting 7.12 fixes to allow for earlier versions to install

- .github/workflows/mvn-deployment-examples-rhpam-charts.yaml
- .github/workflows/mvn-deployment-examples.yaml
- deployment-examples/rhpam-charts/README.md
rhpam-charts are excluded from being checked with shellcheck.
rhpam-charts produce helm charts which causes profound confusion to shellcheck being unable to handle helm chart syntax
They have been therefore excluded from being checked with shellcheck until a suitable workaround can be found
github actions should not report errors on rhpam-charts after commits
> Excluding rhpam-charts from shellcheck

- deployment-examples/pam-eap-setup/pam-setup.sh
Adding gitbash detection for Windows environments. 
Gitbash is a popular alternative to cygwin and shares a lot of functionality.
PAM components should be installing in a gitbash environment in Windows.
> added gitbash detection for pam-eap-setup

- deployment-examples/pam-eap-setup/pam-setup.sh
Any number of EAP system properties can be set at install time through the "pam.config" file. Values containing special characters would misconfigure EAP. 
This fix addresses that by enclosing values in quotes.
EAP system properties values containing special characters would not misconfigure EAP
> allow for complex values on system properties

- deployment-examples/operator-yaml/kieapp-rhpam-authoring-with-git-hooks.yaml
- deployment-examples/operator-yaml/kieapp-rhpam-production-immutable-with-nexus.yaml
Added more kie-app yaml examples that cover the following setup requirements:
a.) rhpam authoring with external nexus
b.) rhpam authoring with git-hooks
Could be tested by feeding these yamls to RHBA operator
> Added more kie-app yaml examples

- deployment-examples/pam-eap-setup/CHANGELOG
- deployment-examples/pam-eap-setup/README.md
- deployment-examples/pam-eap-setup/pam-setup.sh
Added support for RHPAM.7.13 to pam-eap-stup
pam-eap-setup should be able to handle RHPAM.7.13 for local installation
> Added RHPAM.7.13.0 support to pam-eap-setup

- deployment-examples/pam-eap-setup/pam-setup.sh
Added support for RHPAM.7.13.1 to pam-eap-setup
Using RHPAM.7.13.1 binaries should install to a local EAP instance
> added support for RHPAM.7.13.1
