redhat-cop/businessautomation-cop

bcgithook/LICENSE, bcgithook/README.md, bcgithook/install.sh, bcgithook/scripts/default.conf.example, bcgithook/scripts/post-commit.sh
Bash-based implementation for Busness Central post-commit git hooks.
See also: https://trello.com/c/3rhn7EyB
=> added bcgithook files

bcgithook/scripts/post-commit.sh
Will keep using origin URL of imported projects instead of inferring one for pushing to remote repos.
This allows for importing projects with different project names than repository names.
=> imported projects dont get their origin overwritten

pam-eap-setup/CHANGELOG, pam-eap-setup/README.md, pam-eap-setup/addons/node1_config, pam-eap-setup/addons/node2_config, pam-eap-setup/addons/node3_config, pam-eap-setup/addons/node4_config, pam-eap-setup/pam-setup.sh, pam-eap-setup/pam.config, pam-eap-setup/settings.xml
Introduces pam-eap-setup for quick, easy and flexible installation of single or multi-node RHPAM instances on EAP nodes.
See also: https://trello.com/c/glESMTtn
=> pushing pam-eap-setup

pam-eap-setup/CHANGELOG, pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh, pam-eap-setup/pam.config
Added configuration for Oracle datasource
Added configurabe installation directory
Added JVM -Xmx configuration support
Documented DEBUG logging, Oracle datasource definition, specifying install location
Refactored more configuration to use EAP CLI commands
Tested against JBoss EAP patch 8
=> added Oracle datsource, install location, debug logging, documentation

pam-eap-setup/CHANGELOG, pam-eap-setup/pam-setup.sh
Fixed regression preventing EAP configuration from being applied
=> fixed regression on EAP configuration

pam-eap-setup/CHANGELOG, pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh, pam-eap-setup/pam.config
=> added support for PAM.7.7.1

pam-eap-setup/README.md, pam-eap-setup/pam.config
Oracle dialect could be defined according to KB4460791
Modified `pam.config` to include optional dialect configuration
=> updated Oracle dialect based on KB4460791

pam-eap-setup/CHANGELOG, pam-eap-setup/pam-setup.sh
Installation oath specified in the command line can now be a full path
=> allows for full path at installation path

LICENSE
Its good practice to call out what license the repo comes under. all other CoP repos follow Apache
=> Added apache license

.github/workflows/mvn-pam-quick-examples.yaml, pam-quick-examples/dmn-example1/build.sh, pam-quick-examples/dmn-example2/build.sh, pam-quick-examples/dmn-example3/build.sh, pam-quick-examples/dmn-example4/build.sh
=> Added ci for pam-quick-examples

.github/workflows/mvn-bdd-ui.yaml
=> Added ci build for bdd-ui

.github/workflows/mvn-kogito-quick-start-workshop.yaml
=> Added ci for kogito-quick-start-workshop

OWNERS
The other repos use a bot to check who can merge PRs, makes life a lot easier. That bot needs this file.
=> Added owners file

.github/workflows/mvn-offliner-maven-plugin.yaml
Added github action to build code
=> Added ci for offliner-maven-plugin

.gitmodules
https://github.com/redhat-cop/businessautomation-cop/issues/67
=> Removed git submodules config

bcgithook/install.sh
=> Updated git links to be CoP github

.github/PULL_REQUEST_TEMPLATE.md
=> Added github PR template to make it easier for requests / reviewers

pam-quick-examples/dmn-example1/run.sh, pam-quick-examples/dmn-example2/run.sh, pam-quick-examples/dmn-example3/run.sh, pam-quick-examples/dmn-example4/run.sh, pam-quick-examples/dmn-example5/run.sh, pam-quick-examples/dmn-example6/run.sh
Adds handling for unknown option (https://github.com/koalaman/shellcheck/wiki/SC2220)
CC @ippul 
=> Added unknown option handling for run.sh

.github/workflows/shellcheck.yaml, bcgithook/install.sh, bcgithook/scripts/post-commit.sh
Adds spellcheck (linting for bash scripts) to ci
- https://github.com/garethahealy/businessautomation-cop/runs/746602295?check_suite_focus=true
=> Added shellcheck to ci

pam-quick-examples/dmn-example1/build.sh, pam-quick-examples/dmn-example2/build.sh, pam-quick-examples/dmn-example3/build.sh, pam-quick-examples/dmn-example4/build.sh, pam-quick-examples/dmn-example5/build.sh, pam-quick-examples/dmn-example6/build.sh
Few more shellcheck fixes - https://github.com/koalaman/shellcheck/wiki/SC2086
Check the CI builds
=> Added quotes around build variables to stop globbing

pam-quick-examples/dmn-example1/run.sh, pam-quick-examples/dmn-example2/run.sh, pam-quick-examples/dmn-example3/run.sh, pam-quick-examples/dmn-example4/run.sh, pam-quick-examples/dmn-example5/run.sh, pam-quick-examples/dmn-example6/run.sh
Few more shellcheck fixes - https://github.com/koalaman/shellcheck/wiki/SC2086
Clone the PR and execute the run.sh - since I've not got pam on my laptop, would be good @ippul can just give this a once over, to double-check I've not broken anything.
=> Added quotes around run variables to stop globbing

pam-quick-examples/dmn-example1/README.adoc, pam-quick-examples/dmn-example2/README.adoc, pam-quick-examples/dmn-example3/README.adoc, pam-quick-examples/dmn-example4/README.adoc, pam-quick-examples/dmn-example5/README.adoc, pam-quick-examples/dmn-example6/README.adoc
=> Added syntax highlighting to code snippets for pam-examples

bcgithook/README.md
=> Added syntax highlighting to code snippets for bcgithook

pam-eap-setup/README.md
=> Added syntax highlighting to code snippets for pam-setup

kogito-quick-start-workshop/apps/barista/README.md, kogito-quick-start-workshop/apps/coffee-shop/README.md
=> Added syntax highlighting to code snippets for kogito-examples

bdd-ui/feature-file-helper-back-end/README.md, bdd-ui/feature-file-helper-front-end/README.md, bdd-ui/maven-java-bdd-demo/README.md
=> Added syntax highlighting to code snippets for bdd

README.md
=> Updated title syntax for readme

.github/workflows/build-bdd-ui.yaml, .github/workflows/mvn-kogito-quick-start-workshop.yaml, .github/workflows/mvn-offliner-maven-plugin.yaml, .github/workflows/mvn-pam-quick-examples.yaml, offliner-maven-plugin/README.md
=> Updated ci to only trigger on changed files under their directory

.github/workflows/build-bcgithook.yaml, .github/workflows/build-bdd-ui.yaml, .github/workflows/build-pam-eap-setup.yaml, .github/workflows/mvn-kogito-quick-start-workshop.yaml, .github/workflows/mvn-offliner-maven-plugin.yaml, .github/workflows/mvn-pam-quick-examples.yaml
=> Added triggers to workflow changes for ci as well

.github/workflows/build-bdd-ui.yaml, bdd-ui/maven-java-bdd-demo/jenkins/scripts/deliver.sh
=> Added shellcheck for bdd-ui ci

.github/workflows/build-bdd-ui.yaml, .github/workflows/mvn-kogito-quick-start-workshop.yaml, .github/workflows/mvn-offliner-maven-plugin.yaml, .github/workflows/mvn-pam-quick-examples.yaml
Adds macOs and windows as test platforms
Check action output.
=> Added OS to other CI jobs which are mvn based

pam-quick-examples/README.adoc
Tidy up the typos in the readme
👀 
=> 🕵️‍♂️ Tidy up typos in README 👀

CONTRIBUTING.md
Added CONTRIBUTING guide
No testing procedures. This is documentation.
=> Added CONTRIBUTING guide

.github/workflows/build-bcgithook.yaml, bcgithook/scripts/post-commit.sh
Increased robustness of post-commit script by quoting vars
Should work as before
=> fixed variable quoting

pam-quick-examples/dmn-example1/run.sh, pam-quick-examples/dmn-example2/run.sh, pam-quick-examples/dmn-example3/run.sh, pam-quick-examples/dmn-example4/run.sh, pam-quick-examples/dmn-example5/run.sh, pam-quick-examples/dmn-example6/run.sh
Fixes run.sh for pam-examples to work with new request file names
@ippul ; look good? still work?
=> Updated GAV name to match json file due to : vs _ change

README.md
The build status is for another repo, so shouldn't be in this readme.
=> Removed build status

.github/workflows/build-bdd-ui.yaml, .github/workflows/build-pam-vagrant.yaml, .github/workflows/mvn-pam-quick-examples.yaml
As per subject.
Check action output.
=> Added pam-vagrant ci

bcgithook/install.sh, bcgithook/scripts/post-commit.sh
Addressing shellchecks shouts.
There should be no change in functionality.
=> addressing shellchecks shouts

bcgithook/install.sh, bcgithook/scripts/post-commit.sh
Addressed some issues raised by shellcheck and added directives to fine tune its opearation
Functionality should have remained the same
=> added shellcheck directives

.github/workflows/build-pam-eap-setup.yaml, pam-eap-setup/pam-setup.sh
Check for empty options before applying them.
Add shellcheck directives against non-applicable checks
Invoke with empty options, i.e. -o :
=> Check for empty options and shellcheck directives

.github/workflows/build-pam-eap-setup.yaml, pam-eap-setup/pam-setup.sh
Addressed some suggestions by shellcheck.
No new functionality.
=> addressed some shellcheck suggestions

.github/workflows/build-bcgithook.yaml, bcgithook/README.md
Provide documentation for the ALLOW and DENY configuration options in bcgithook.
Tune shellcheck operation
Documentation changes. Not new functionality implemented.
=> document ALLOW and DENY configuration options

pam-eap-setup/pam-setup.sh
Fixing regression as reported on https://github.com/redhat-cop/businessautomation-cop/issues/133
https://github.com/redhat-cop/businessautomation-cop/issues/133 should be fixed
=> fixing regression errors

pam-eap-setup/pam-setup.sh
Removed not required dependency checks for curl and maven
No new functionality implemented
=> removed unneeded dependencies

.github/workflows/build-pam-eap-setup.yaml, pam-eap-setup/CHANGELOG
Added EAP.7.2.8 patch to github workflow build of pam-setup
EAP.7.2.8 should be downloaded and installed
=> Added EAP.7.2.8 patch to github workflow build of pam-setup

.github/workflows/build-bdd-ui.yaml
https://github.com/redhat-cop/businessautomation-cop/pull/138#pullrequestreview-438050616
Check ci passes
=> Updated bdd ci to be node12

bcgithook/README.md, bdd-ui/README.md, kogito-quick-start-workshop/README.md, offliner-maven-plugin/README.md, pam-eap-setup/README.md, pam-quick-examples/README.adoc, pam-vagrant/README.md
=> Added ci badges to all readmes

.github/workflows/build-bdd-ui.yaml
=> Removed --no-audit from npm for bdd ci

.github/workflows/build-bcgithook.yaml, .github/workflows/build-pam-eap-setup.yaml, .github/workflows/build-pam-vagrant.yaml, bcgithook/install.sh, pam-eap-setup/pam-setup.sh
=> Added inline shellcheck skips for eap to stop ci failing

pam-quick-examples/README.adoc, pam-quick-examples/dmn-example1/README.adoc, pam-quick-examples/dmn-example1/dmn-example1-parent/dmn-example1-kie-api-remote-impl/src/main/java/com/redhat/cop/pam/example1/kie/api/impl/RulesApiImpl.java
=> Pam quick examples/dmn example1/fix readme

pam-eap-setup/README.md
Update documentation for pam-eap-setup to include configuration through pam.config file
Documentation updates only.
=> updated documentation for pam.config

pam-quick-examples/README.adoc, pam-quick-examples/dmn-example1/README.adoc, pam-quick-examples/dmn-example2/README.adoc, pam-quick-examples/dmn-example3/README.adoc, pam-quick-examples/dmn-example4/README.adoc, pam-quick-examples/dmn-example5/README.adoc, pam-quick-examples/dmn-example6/README.adoc
fix some error and broke link in readme
no test needed
=> fix readme

pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh
Adding documentation for option to configure RHPAM run mode
Documentation changes
=> Adding documentation for RHPAM run mode configuration

pam-eap-setup/pam-setup.sh
Added option to install bcgthook post-commit git hook implementation with the same invocation of pam-setup.sh
Post commit git hook should be installed in JBOSS_HOME/git-hooks directory.
=> added option to install bcgithook along with RHPAM

bcgithook/README.md
Updated README to disambiguate handling of new repositories in certain git backends
Documentation updates
=> Updated bcgithook README

.github/workflows/mvn-pam-quick-examples.yaml
$subject
Action should go green
=> Added spring-boot-* examples to ci

pam-eap-setup/README.md
=> Update pam-eap-setup README with git hook integration options

.github/workflows/mvn-pam-quick-examples.yaml, pam-quick-examples/integration-create-instance/pom.xml
Added Paul Browns project to CI
run CI
=> Added Quarkus project to github CI

pam-eap-setup/pam-setup.sh
=> Added integration for kiegroup post-commit git hooks

pam-quick-examples/integration-create-instance/src/main/java/org/acme/CreateProcessFromEmail.java
=> Added a file based poller to start a process instance

.github/actions/eap-base/Dockerfile, pam-eap-setup/pam-setup.sh
Added checks to pam-eap-setup for maven and updated eap-base to include maven in the list of packages to install
pam-eap-setup should be able to install rhpam
=> added maven to eap-base and added checks to pam-eap-setup

pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh
=> Updated documentation for kiegroup post-commit git hook integration

pam-eap-setup/pam-setup.sh
Updated pam-eap-setup help text to clarify handling of additional configuration files
Documentation changes only.
=> updated help text

pam-eap-setup/CHANGELOG, pam-eap-setup/README.md
Configuring EAP through pam-eap-setup has been documented.
Documentation only changes.
=> updated README for EAP configuration

pam-quick-examples/spring-boot-examples/deployments/kie-sboot-deployments-spring-props/pom.xml, pam-quick-examples/spring-boot-examples/kie-sboot-seed/pom.xml, pam-quick-examples/spring-boot-examples/persistence/kie-sboot-pvp/pom.xml, pam-quick-examples/spring-boot-examples/pom.xml, pam-quick-examples/spring-boot-examples/queries/kie-sboot-advanced-query/pom.xml, pam-quick-examples/spring-boot-examples/security/kie-sboot-security-basic-auth/pom.xml, pam-quick-examples/spring-boot-examples/security/kie-sboot-security-sso/pom.xml, pam-quick-examples/spring-boot-examples/security/kie-sboot-security-unsecure/pom.xml, pam-quick-examples/spring-boot-examples/transactions/kie-sboot-xa-tx-db/pom.xml
Upgrade to PAM 7.8 & Removed Jackson Overrided libs
built it
=> 7.8 upgrade

docs/README.md, docs/api/index.html
=> Added all specs & new links in Readme

docs/api/index.html, docs/api/spec/pam-swagger-7.4.0.json
=> added KIE 7.4.0 Swagger spec

pam-eap-setup/pam-setup.sh
Add PAM 7.8.0 and PostgreSQL data source support
=> Patch 2: PAM 7.8.0 and postgresql datasource support

pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh
Updated pam-eap-setup documentation for RHPAM.7.8 and PostgreSQL options
Documentation changes only
=> updated documentation for PAM.7.8 and PostgreSQL

pam-eap-setup/pam-setup.sh
Multiple EAP config files can be specified in a comma-separated list.
Makes it easier to have development environments with different configurations off a base one
Specify multiple EAP configuration files, should all be applied
=> support for multiple EAP config files

README.md
Changing spelling mistakes and adding fullstops to make it uniform across the page.
=> Spelling mistake correction

pam-eap-setup/pam-setup.sh
=> added support for RHPAM.7.8.1

pam-eap-setup/README.md
README has been updated for RHPAM.7.8.1
Documentation changes only
=> updated docs for RHPAM.7.8.1

pam-quick-examples/dmn-examples/README.adoc
=> Fixed documentation in pam-quick-examples/dmn-examples

pam-eap-setup/pam-setup.sh
Added option to create log file of installation.
If option "logfile" is used, file "pam-setup.log" should be created.
=> optionally create log file of installation

pam-eap-setup/CHANGELOG, pam-eap-setup/README.md, pam-eap-setup/pam-setup.sh
Ase per $subject
Documentation changes, mainly.
=> added documentation for installation log

pam-vagrant/README.md, pam-vagrant/bootstrap.sh, pam-vagrant/pam-setup.sh, pam-vagrant/pam7-systemd-integration.sh
Placing RHPAM.7.8.1 and EAP.7.3.x files in pam-vagrant folder and invoking vagrant a vagrant box should be installed with RHPAM.7.8.1 and Nexus listening on ports 8080 and 8081 respectively
=> pam-vagrant updated for RHPAM.7.8.1

bcgithook/README.md
Updated documentation for the bcgithook project with the optional BANCH_MAP option
No code changes.
=> Documented bcgithook BRANCH_MAP option

pam-eap-setup/pam.config
No code changes, no visible changes unless the configuration is enabled
=> Added optional configuration for increasing process variable value storage

pam-quick-examples/dmn-examples/dmn-open-account-bdd-example/README.adoc
Some broken links were fixed in DMN BDD doceumentation
=> Fixed some broken links in DMN BDD pam-quick-examples

.github/workflows/mvn-data-generator.yaml, .github/workflows/mvn-task-automator.yaml
As per subject.
CI should pass - have noticed it sometimes fail on Macs, not sure why as linux/windows both pass. The error when it fails is always:
`Transfer failed for https://repo.maven.apache.org/maven2/{what-ever-file-its-trying-to-download}.jar 502 Gateway Error`
which makes me think apache or github are having a bad day.
=> Added ci for task-automator and data-generator

pam-eap-setup/pam-setup.sh
pam-eap-setup should apply patch JBEAP-20659 if EAP.7.3 has been patched to patch level 4
JBEAP-20659 fixes "password vault does not work after 7.3.4"
After 7.3.4 and JBEAP-20659 patches have been applied EAP log should state 
"JBoss EAP cumulative patch ID is: jboss-eap-7.3.4.CP, one-off patches include: eap-734-jbeap-20659"
=> add support for jbeap-20659 to pam-eap-setup

bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/pom.xml, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/context/BDDContext.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/listeners/BDDProcessListener.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/listeners/BDDTaskListener.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/runner/BDDRunner.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/steps/HumanTaskSteps.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/steps/ProcessSteps.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/steps/ScenariosCommons.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/bdd/steps/SubprocessSteps.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/guice/BDDContextServiceModule.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/guice/BDDCustomContextProvider.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/guice/CustomObjectFactory.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/runtime/BDDEmbeddedRuntime.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/runtime/NotSupportedRuntimeStrategyException.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/java/com/redhat/pam/utils/TriFunction.java, bdd-pam-framework/pam-bdd-parent/pam-bdd-junit-commons/src/main/resources/META-INF/services/io.cucumber.core.backend.ObjectFactory, bdd-pam-framework/pam-bdd-parent/pom.xml
rename artifact and package
mvn clean install
=> name refactor

bcgithook/scripts/post-commit.sh
1) Openshift configuration
Configuring [bcgithook](https://github.com/redhat-cop/businessautomation-cop/tree/master/bcgithook) in Openshift is not straightforward requiring editing of the post-commit script to specify custom configuration directories.
This PR takes advantage of the "GIT_HOOKS_DIR" environment variable set by the PAM operator and uses it to locate configuration files
2) Separate configuration per BC installation
In case of multiple Business Central installations (in the same machine/VM) providing different configurations for [bcgithook](https://github.com/redhat-cop/businessautomation-cop/tree/master/bcgithook) is not straightforward requiring editing of the post-commit script to specify custom configuration directories.
This PR takes advantage of the JBOSS_HOME …
=> Configuring BC git hooks for Openshfit and for multiple installations

bdd-pam-framework/pam-bdd-examples/project-to-test-with-bdd-parent/project-to-test-with-bdd-junit-test/src/test/java/com/redhat/examples/guice/ContextProvider.java
replaced hardcoded kjar GAV with system property
mvn clean install -P junit-test
=> replaced hardcoded kjar GAV with system property

.github/workflows/build-deployment-examples.yaml, .github/workflows/mvn-coded-examples.yaml, .github/workflows/mvn-deployment-examples.yaml, .github/workflows/mvn-extras.yaml, .github/workflows/mvn-migration-examples.yaml, .github/workflows/mvn-testing-examples.yaml, .github/workflows/mvn-workshops.yaml
=> fix longpaths issue for windows ci builds

testing-examples/bdd-pam-framework/pom.xml
cucumber version upgraded
mvn clean install
=> cucumber version upgraded

deployment-examples/pam-eap-setup/README.md
Updated the link to bcgithook to point to the correct location
=> Fixed broken link to bcgithook 

deployment-examples/pam-eap-setup/README.md, deployment-examples/pam-eap-setup/pam-setup.sh
Update pam-eap-setup to handle RHPAM.7.10.1
pam-eap-setup should be able to install RHPAM.7.10.1
=> updated pam-eap-setup for rhpam.7.10.1

extras/bcgithook/README.md
Update bcgithook documentation to reflect latest product announcements
=> updated bcgithook documentation

extras/bcgithook/README.md, extras/bcgithook/install.sh
(a) provides working help option for bcgithhook installation script
(b) provides installation time options "global" and "local" for specifying bcgithook configuration location
Using the installation script should install bcgithooks to an existing EAP-based RHPAM/RHDM instance
=> introduce and document global and local configuration options for bcgithook

extras/bcgithook/README.md
Fixed the typo errors.
Fix for the typo errors in README.md
Manual verification would be required. 
=> Fixed typos

extras/bcgithook/README.md
Update bcgithook documentation for git-ssh URLs support
=> Documenting support for git-ssh style URLs

extras/bcgithook/README.md
Document configuration options for per-project configuration files for bcgithook
No code is affected
=> document project specific URLs for per-project configuration

deployment-examples/pam-eap-setup/README.md
Business Central installed by pam-eap-setup logs projects/spaces deletion as per https://access.redhat.com/solutions/6139932
No code is changed in this commit.
=> document additional logging for BC

deployment-examples/pam-eap-setup/pam-setup.sh
sed in OS X is named gsed and that causes superfluous error messages during installation messages.
Although a workaround exists for homebrew it may not have been applied blocking the installation.
This fix attempts to detect the name sed is called with in an OS X environment and uses that instead of "sed".
RHPAM should be installed in an OS X environment regardless of the homebrew workaround for sed being present or not
=> address potential issue with sed in OS X

deployment-examples/pam-eap-setup/README.md, deployment-examples/pam-eap-setup/pam-setup.sh
Java version is not properly sanitized before evaluation, could potentially be an issue, although currently it is not.
This PR fixes that.
Installation should complete as usual.
=> fixes in java version detection

coded-examples/business-central/onboarding/src/main/resources/com/onboarding/onboarding/DocumentCheck.bpmn
=> Changed task name to test

deployment-examples/using-the-rest-api/README.md
Created directory and initial README file for deployments using the REST API of BC and KIE Servers
Does not contain any code.
=> Deployments using the REST API

deployment-examples/using-the-rest-api/README.md, deployment-examples/using-the-rest-api/config.properties, deployment-examples/using-the-rest-api/deploy-kjar-bc.js
A script for deploying KJARs using the REST endpoints exposed by Business Central is provided.
Documentation fixes.
The deploy-kjar-bc.js scripts should be able to deploy a KJAR through Business Central
=> Added script for KJAR deployment using BC REST API

deployment-examples/using-the-rest-api/README.md
Updated documentation on the Using REST API for deployment example
=> Updated documentation on deployment/rest-api example

deployment-examples/using-the-rest-api/README.md
Provided documentation about the REST endpoints used for the "Deployment with REST examples"
No code is affected in this PR.
=> Updated documentation for deployment with REST examples

extras/ansible-playbooks/generate-jks-file.yml, extras/ansible-playbooks/readme.adoc
Add under extra folder a new folder for ansible-playbooks that will help with configuration, installation, deployment of RHPAM, DM etc.
=> Add Ansible playbook for assist with configuration, installation, deployment.

docs/api/index.html, docs/api/spec/bc-swagger-7.11.1.json, docs/api/spec/kie-swagger-7.11.1.json
Updated the COP swagger docs with RHPAM 7.11.1 swagger.json
By hosting is at my personal github.io repo - https://bbalakriz.github.io/
=> Added bc and kie swagger files for RHPAM 7.11.1

extras/podman/readme.adoc
Podman composes for RHPAM, RHDM initial commit.
=> initial commit for the Podman composes

docs/api/index.html, docs/api/spec/bc-swagger-7.10.0.json, docs/api/spec/kie-swagger-7.10.0.json
Added swagger docs for RHPAM 7.10.0
Tested by hosting it in my personal repo https://bbalakriz.github.io/
=> Added swagger docs for RHPAM 7.10.0

coded-examples/business-central/single-usertask/openshift/templates/rhpam711-kieserver-postgresql.yaml
=> Change templates timeout

coded-examples/business-central/single-usertask/JenkinsFile
=> Add JenkinsFile kieserver to single-usertask 

coded-examples/business-central/single-usertask/Jenkinsfile-monitoring
=> add JenkinsFile for monitor pipeline to single usertask 

deployment-examples/using-the-rest-api/README.md, deployment-examples/using-the-rest-api/config.properties
Documentation update about available runtime strategies
=> Documentation updates on using rest to deploy

extras/custom-kie-server-image/oracle-drive-image/standalone-openshift.xml
=> add standalone-openshift xml with generic oracle datasource example

extras/custom-kie-server-image/oracle-drive-image/Dockerfile
=> Add DockerFile to copy oracle module and openshift-standalone.xml 

extras/custom-kie-server-image/oracle-drive-image/install.properties
=> add install properties for oracle drive

extras/custom-kie-server-image/build.sh
=> add build script for oracle drive

extras/custom-kie-server-image/install.sh
=> add install script for oracle drive

extras/custom-kie-server-image/README.md
=> add ReadMe file

deployment-examples/using-the-rest-api/deploy-kjar-kie.js, extras/custom-kie-server-image/install.sh
Adds example of deploying KJAR to KIE Server using the REST API.
Documentation pending.
example usage: ./deploy-kjar-kie.js localhost:8280:geo280:com.bacop.jwt_dm_project:rules:2.4-SNAPSHOT
=> example of kjar deployment using rest api of kie server

extras/custom-kie-server-image/build.sh
Fix variable syntax adding double quotes around them.
=> Fix variable syntax

extras/custom-kie-server-image/build.sh
Sanitizing variable usage on build.sh shell script
There are no changes other than variable quoting
=> Sanitizing build.sh shell script

deployment-examples/using-the-rest-api/config.properties, extras/custom-kie-server-image/build.sh
Quotes shell script variables to prevent splitting
Image should be building. No material change made.
=> build.sh sanity fixes

coded-examples/business-central/single-usertask/JenkinsFile
=> Update Jenkins KieServer pipeline

README.md
=> Update Main README file

coded-examples/business-central/single-usertask/JenkinsFile
=> Update JenkinsFile on single task process

testing-examples/bdd-pam-framework/pam-bdd-examples/project-to-test-with-bdd-parent/project-to-test-with-bdd-wih/pom.xml
=> Update Junit version

deployment-examples/using-the-rest-api/README.md
Updated README of the deployment with REST section
Documentation only changes
=> updated README

coded-examples/dmn-examples/dmn-jbpm-ext-kjar-example/project/kjars/process-kjar/pom.xml
=> Update Junit test

deployment-examples/pam-eap-setup/pam-setup.sh
Support for 7.12 and EAP 7.4 Elytron
I also changed the configuration to be based on `standalone-full` (no HA) the target is DM as HA is not needed for DM Kie Servers.
=> Patch 5: Support for 7.12 and EAP 7.4 Elytron

coded-examples/dmn-examples/dmn-jbpm-ext-kjar-example/project/kjars/dmn-kjar/pom.xml
xstream is updated to non-vulnerable version
All checks should continue to pass
=> updating vulnerable xstream version

coded-examples/dmn-examples/dmn-open-account-java-func-example/project/kjar/pom.xml
Updated version of xstream to latest
All check should continue to pass
=> updated vulnerable xstream version

deployment-examples/using-the-rest-api/README.md
Updated documentation of REST deployment for the case of direct deployment to a KIE Server
=> Updated docs for REST deployment

deployment-examples/pam-eap-setup/README.md
Updated documentation for pam-eap-setup
No code changes.
=> updated documentation for pam-eap-setup

README.md
=> Update READMe page

extras/ansible-playbooks/jboss-patch-apply.yml
=> Added ansible JBoss patch apply playbook

deployment-examples/pam-eap-setup/README.md
Update documentation of pam-eap-setup for RHPAM 7.12
Documentation only updates, no code changes
=> documentation updates for RHPAM.7.12

extras/bcgithook/README.md
Updated bcgithook documentation for RHPAM.7.12.0
No code changes, documentation only.
=> Update bcgithook documentation

docs/README.md
The README for /docs has been updated
No code changes, documentation only
=> Updates on docs/README

coded-examples/jbpm-examples/README.adoc
=> create a new area for jbpm re usable examples

.github/workflows/mvn-extras.yaml, extras/data-generator/pom.xml
Updated github actions for extras to include Red Hat GA maven repos for JDK.11 builds
Builds should finish without errors.
=> Update github actions for extras

deployment-examples/pam-eap-setup/pam-setup.sh
RHDM.7.12.1 should be able to et installed with the fixes included in this PR
RHDM.7.12.1 should be installed with no issues
=> pam-eap-setup fixes for RHDM.7.12.1

deployment-examples/pam-eap-setup/README.md
Documenting pam-eap-stup fetching required users from ldap.
Documentation only, no code changes
=> Documenting unmanaged installation for KIE Servers

extras/ansible-jboss-cli/README.adoc
=> inital commit ansible jboss-cli

extras/ansible-jboss-cli/jboss-version.yml
=> Add jboss version yml

extras/ansible-jboss-cli/jboss-patch-apply.yml
=> Add jboss patch apply

extras/ansible-jboss-cli/jboss-log-location.yml
=> Add jboss log

extras/ansible-jboss-cli/jboss-log-level.yml
=> Add jboss log level

extras/ansible-jboss-cli/jboss-bound-port.yml
=> jboss bound port

deployment-examples/pam-eap-setup/README.md
Documentation updates
No code has been changed
=> Update pam-eap-setup documentation for CORS on OCP

deployment-examples/pam-eap-setup/README.md
Document unmanaged KIE Server installation options
=> updated pam-eap-setup README

workshops/README.md
Updated workshop sections with content about Users, Groups, RuleFlows and Decision Tables.
=> Updated Workshops section

docs/api/index.html, docs/api/spec/bc-swagger-7.12.0.json, docs/api/spec/kie-swagger-7.12.0.json
Swagger specs are updated for RHPAM.7.12.0 for BC and KIE Server
Documentation only updates
=> Update swagger specs for RHPAM.7.12.0

docs/api/index.html, docs/api/spec/bc-swagger-7.12.1.json, docs/api/spec/kie-swagger-7.12.1.json
BC and KIE swagger specs in the docs section have been updated for the RHPAM.7.12.1 release
=> updated swagger specs for RHPAM.7.12.1

deployment-examples/pam-eap-setup/pam-setup.sh
In response to https://github.com/redhat-cop/businessautomation-cop/issues/440
BC and KIE in different nodes should be installed with no issues
=> address issue 440

deployment-examples/operator-yaml/kieconfig/kieconfigs-7.10.0-custom-with-volume-mnt.yaml
Added a sample kie-config yaml that shows how to do mount custom volumes for hosting custom files that might be required for accessing from kie-containers
Could be tested by supplying the provided yamls to RHBA operator on Openshift
=> Sample KieConfig yaml with custom volume mounts

deployment-examples/operator-yaml/bc-git-hooks-config-operator-templates.md
Added a "how-to" for setting up the BC githooks on a RHBA operator controlled rhpam-authoring environment as well as with RHPAM templates
By applying the documented steps on RHBA operator in Openshift
=> "How-to" for setting up BC githooks on RHBA operator

deployment-examples/pam-eap-setup/pam-setup.sh
pam-eap-setup has been updated for RHPAM.7.13.2
=> updated for RHPAM.7.13.2

deployment-examples/pam-eap-setup/README.md
Docs updated for pam-eap-setup
=> updated docs for RHPAM.7.13.1 and 7.13.2

.github/workflows/mvn-coded-examples.yaml, .github/workflows/mvn-deployment-examples-rhpam-charts.yaml, .github/workflows/mvn-deployment-examples.yaml, .github/workflows/mvn-extras.yaml, .github/workflows/mvn-migration-examples.yaml, .github/workflows/mvn-testing-examples.yaml, .github/workflows/mvn-workshops.yaml
will allow this to be merged:
- https://github.com/redhat-cop/businessautomation-cop/pull/464
green ci
=> added distribution for v3 java action

.github/workflows/mvn-coded-examples.yaml
Updated Java version to 8.0.362+9 fro Temurin allowing github action jobs to complete
Github action jobs should complete for ubuntu/mvn-coded-examples.yaml
=> updated java version

.github/workflows/mvn-coded-examples.yaml, .github/workflows/mvn-deployment-examples-rhpam-charts.yaml, .github/workflows/mvn-deployment-examples.yaml, .github/workflows/mvn-extras.yaml, .github/workflows/mvn-migration-examples.yaml, .github/workflows/mvn-workshops.yaml
[fixes ci](https://github.com/redhat-cop/businessautomation-cop/actions/runs/4311819766/jobs/7521628407)
green ci
=> fix for ci

coded-examples/business-central/pom.xml, coded-examples/dmn-examples/pom.xml, coded-examples/kie-server-extensions/pom.xml
=> removed release to fix ci

.github/workflows/mvn-coded-examples.yaml, .github/workflows/mvn-deployment-examples-rhpam-charts.yaml, .github/workflows/mvn-deployment-examples.yaml, .github/workflows/mvn-extras.yaml, .github/workflows/mvn-migration-examples.yaml, .github/workflows/mvn-testing-examples.yaml, .github/workflows/mvn-workshops.yaml
caches were at 99% usage. this should keep it lower
=> removed hash so its a cache per build and os

coded-examples/spring-boot-examples/README.adoc
Fixed lists and indentation in documentation
No code chnages
=> documentation fixes

coded-examples/spring-boot-examples/drools/drools-sboot-embedded/README.md
Updated ReadMe of subject with a reference to specific spring-boot version
=> Update Readme of coded-examples/spring-boot/drools
